const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Timer,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Camera3D,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Shape3D.Acts.MoveToTop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Acts.SetZ,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Acts.AddInstanceVar,
		C3.Plugins.Shape3D.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Sprite.Acts.SetZ,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Shape3D.Cnds.CompareZ,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Shape3D.Exps.Count,
		C3.Plugins.Shape3D.Exps.Z,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AdvancedRandom.Exps.WeightedByName
	];
};
self.C3_JsPropNameTable = [
	{HP: 0},
	{MaxHP: 0},
	{Damage: 0},
	{Speed: 0},
	{AttackRate: 0},
	{Range: 0},
	{HPPickupPercentage: 0},
	{PlayerBillboard: 0},
	{AttackAngle: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{PlayerCollision: 0},
	{PlayerTexture: 0},
	{DistanceToPlayer: 0},
	{Sine: 0},
	{Timer: 0},
	{Fade: 0},
	{HealthPickup: 0},
	{HealthTexture: 0},
	{Rotate: 0},
	{PremiumPickup: 0},
	{CoinPickup: 0},
	{CoinTexture: 0},
	{DamagePlayer: 0},
	{Pin: 0},
	{HealthBar: 0},
	{Health: 0},
	{Cooldown: 0},
	{RoomID: 0},
	{Pathfinding: 0},
	{Enemy: 0},
	{Active: 0},
	{EnemySpawner: 0},
	{ID: 0},
	{IsHurt: 0},
	{HurtTimer: 0},
	{EnemyTexture: 0},
	{BossSpawner: 0},
	{Boss: 0},
	{BossTexture: 0},
	{"3DCamera": 0},
	{AdvancedRandom: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{Solid: 0},
	{Wall: 0},
	{Wall1: 0},
	{Wall2: 0},
	{Roof1: 0},
	{Roof2: 0},
	{IsOpen: 0},
	{Door: 0},
	{OnCollision: 0},
	{DoorCollision: 0},
	{TextBuyDoor: 0},
	{UIBuyDoor: 0},
	{DoorTexture: 0},
	{RoofDoor: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{Tween: 0},
	{BulletTexture: 0},
	{LevelUp: 0},
	{XpBar: 0},
	{Background: 0},
	{Tilemap: 0},
	{Assets: 0},
	{Enemies: 0},
	{BossRoom: 0},
	{RoomTrigger: 0},
	{Coins: 0},
	{Premium: 0},
	{ClosestDistance: 0},
	{ClosestEnemy: 0},
	{Xp: 0},
	{XpNeeded: 0},
	{Level: 0},
	{LastEnemyX: 0},
	{LastEnemyY: 0},
	{EnemyCountStart: 0},
	{EnemyCount: 0},
	{AllEnemiesDied: 0},
	{WaveNumber: 0},
	{Type: 0},
	{RandomNumber: 0},
	{DropThreshold: 0},
	{DropType: 0}
];

self.InstanceType = {
	PlayerBillboard: class extends self.I3DShapeInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	PlayerTexture: class extends self.ISpriteInstance {},
	HealthPickup: class extends self.I3DShapeInstance {},
	HealthTexture: class extends self.ISpriteInstance {},
	PremiumPickup: class extends self.I3DShapeInstance {},
	CoinPickup: class extends self.I3DShapeInstance {},
	CoinTexture: class extends self.ISpriteInstance {},
	DamagePlayer: class extends self.I3DShapeInstance {},
	HealthBar: class extends self.I3DShapeInstance {},
	Enemy: class extends self.I3DShapeInstance {},
	EnemySpawner: class extends self.ISpriteInstance {},
	EnemyTexture: class extends self.ISpriteInstance {},
	BossSpawner: class extends self.ISpriteInstance {},
	Boss: class extends self.I3DShapeInstance {},
	BossTexture: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Wall: class extends self.I3DShapeInstance {},
	Wall1: class extends self.ISpriteInstance {},
	Wall2: class extends self.ISpriteInstance {},
	Roof1: class extends self.ISpriteInstance {},
	Roof2: class extends self.ISpriteInstance {},
	Door: class extends self.I3DShapeInstance {},
	DoorCollision: class extends self.ISpriteInstance {},
	TextBuyDoor: class extends self.ITextInstance {},
	UIBuyDoor: class extends self.I3DShapeInstance {},
	DoorTexture: class extends self.ISpriteInstance {},
	RoofDoor: class extends self.ISpriteInstance {},
	Bullet: class extends self.I3DShapeInstance {},
	BulletTexture: class extends self.I3DShapeInstance {},
	LevelUp: class extends self.ISpriteInstance {},
	XpBar: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Assets: class extends self.ISpriteInstance {},
	RoomTrigger: class extends self.ISpriteInstance {}
}